const assert = require('node:assert/strict');
const fs = require('node:fs');
const http = require('node:http');
const {fixture} = require('./browser.test.cjs');
const moduleRoot = process.env.SELENIUM_MODULE_ROOT || 'selenium-webdriver';
const {Builder,By} = require(moduleRoot);
const firefox = require(moduleRoot+'/firefox');
async function main() {
  const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html;charset=utf-8');res.end(fixture);});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  let driver;
  try {
    const options=new firefox.Options().addArguments('-headless');
    if(process.env.FIREFOX_BINARY)options.setBinary(process.env.FIREFOX_BINARY);
    const builder=new Builder().forBrowser('firefox').setFirefoxOptions(options);
    if(process.env.GECKODRIVER)builder.setFirefoxService(new firefox.ServiceBuilder(process.env.GECKODRIVER));
    driver=await builder.build();
    await driver.manage().window().setRect({width:1400,height:1100});
    await driver.get('http://127.0.0.1:'+server.address().port);
    await driver.wait(()=>driver.executeScript('return window.ready||false'),10000);
    assert.equal((await driver.findElements(By.css('.cbi-tabmenu > li'))).length,9);
    await driver.findElement(By.css('#tab-advanced a')).click();
    assert.equal(await driver.findElement(By.id('advanced-caching')).getAttribute('open'),null);
    await driver.findElement(By.css('#advanced-caching summary')).click();
    assert.equal(await driver.findElement(By.css('[name="cache_size"]')).isDisplayed(),true);
    await driver.findElement(By.css('#tab-config_view a')).click();
    const original=await driver.findElement(By.id('config-textarea')).getAttribute('value');
    await driver.executeScript("const t=document.getElementById('config-textarea');for(let i=1;i<=3;i++){t.value+='\\n# step '+i;t.dispatchEvent(new Event('input'));}");
    for(let i=0;i<3;i++)await driver.findElement(By.xpath('//div[@id="config-view-content"]//button[text()="Назад"]')).click();
    assert.equal(await driver.findElement(By.id('config-textarea')).getAttribute('value'),original);
    await driver.findElement(By.xpath('//div[@id="config-view-content"]//button[text()="Вперёд"]')).click();
    assert.match(await driver.findElement(By.id('config-textarea')).getAttribute('value'),/# step 1$/);
    await driver.findElement(By.xpath('//div[@id="config-view-content"]//button[text()="Назад"]')).click();
    await driver.findElement(By.css('#tab-rules a')).click();
    await driver.findElement(By.xpath('//div[@id="panel-rules"]//button[text()="Загрузить файл"]')).click();
    await driver.wait(()=>driver.executeScript('return !document.querySelector("#panel-rules textarea").disabled'),3000);
    const rules=await driver.findElement(By.css('#panel-rules textarea'));
    await rules.sendKeys('example.test 127.0.0.1:5300');
    await assert.rejects(()=>driver.executeScript('return app.handleSave()'),/правки файла правил/);
    await driver.findElement(By.xpath('//div[@id="panel-rules"]//button[text()="Сохранить"]')).click();
    await driver.wait(()=>driver.executeScript('return files["/etc/dnscrypt-proxy2/forwarding-rules.txt"] === "example.test 127.0.0.1:5300"'),3000);
    await rules.sendKeys('\nsecond.test 127.0.0.1:5400');
    await driver.findElement(By.xpath('//div[@id="panel-rules"]//button[text()="Сохранить"]')).click();
    await driver.wait(()=>driver.executeScript('return (histories["/etc/dnscrypt-proxy2/forwarding-rules.txt"]||[]).length===1'),3000);
    await driver.findElement(By.xpath('//div[@id="panel-rules"]//button[text()="Сохранённые версии"]')).click();
    await driver.wait(()=>driver.executeScript('return !!document.getElementById("modal")'),3000);
    await driver.findElement(By.css('#modal button')).click();
    assert.equal(await rules.getAttribute('value'),'example.test 127.0.0.1:5300');
    assert.match(await driver.executeScript('return files["/etc/dnscrypt-proxy2/forwarding-rules.txt"]'),/second.test/,'Preview must not write the file');
    await driver.findElement(By.xpath('//div[@id="panel-rules"]//button[text()="Назад"]')).click();
    await driver.executeScript('files["/etc/dnscrypt-proxy2/forwarding-rules.txt"] += "\\n# external"');
    await rules.sendKeys('\nthird.test 127.0.0.1:5500');
    await driver.findElement(By.xpath('//div[@id="panel-rules"]//button[text()="Сохранить"]')).click();
    await driver.wait(()=>driver.executeScript('return document.getElementById("notifications").textContent.includes("changed externally")'),3000);
    assert.equal(await driver.executeScript('return files["/etc/dnscrypt-proxy2/forwarding-rules.txt"].includes("third.test")'),false);
    assert.deepEqual(await driver.executeScript('return errors'),[]);
    if(process.env.FORGE_SCREENSHOT)fs.writeFileSync(process.env.FORGE_SCREENSHOT,await driver.takeScreenshot(),'base64');
    console.log('Passed editors: collapsed Advanced, three undo steps, redo, file creation/saving, version preview, no automatic restore and external-change protection');
  } finally {if(driver)await driver.quit();await new Promise(resolve=>server.close(resolve));}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
