const assert = require('node:assert/strict');
const fs = require('node:fs');
const http = require('node:http');
const {fixture} = require('./browser.test.cjs');
const moduleRoot = process.env.SELENIUM_MODULE_ROOT || 'selenium-webdriver';
const {Builder,By} = require(moduleRoot);
const firefox = require(moduleRoot+'/firefox');
const feedbackFixture=fixture.replace('app.load().then', `
files[primary] += "\\n[static.preset-one]\\nstamp = 'sdns://AAAA'\\n[static.preset-two]\\nstamp = 'sdns://BBBB'\\n";
files[primary] = "cloaking_rules = '/etc/dnscrypt-proxy2/cloaking-rules.txt'\\n" + files[primary];
app.load().then`);
async function main() {
  const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html;charset=utf-8');res.end(feedbackFixture.replaceAll('window.location.reload()', 'window.savedReload=true'));});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  let driver;
  try {
    const options=new firefox.Options().addArguments('-headless');
    if(process.env.FIREFOX_BINARY)options.setBinary(process.env.FIREFOX_BINARY);
    const builder=new Builder().forBrowser('firefox').setFirefoxOptions(options);
    if(process.env.GECKODRIVER)builder.setFirefoxService(new firefox.ServiceBuilder(process.env.GECKODRIVER));
    driver=await builder.build();
    await driver.manage().window().setRect({width:1400,height:1100});
    await driver.get('http://127.0.0.1:'+server.address().port);
    await driver.wait(()=>driver.executeScript('return window.ready||false'),10000);
    await driver.findElement(By.css('#tab-servers a')).click();
    assert.equal(await driver.findElement(By.id('custom-servers')).getAttribute('open'),'true');
    assert.match(await driver.findElement(By.id('custom-servers')).getText(),/sdns:\/\/AAAA/);
    assert.match(await driver.findElement(By.id('custom-servers')).getText(),/sdns:\/\/BBBB/);
    const inputs=await driver.findElements(By.css('#panel-servers details input'));
    assert.equal(await inputs[0].getAttribute('value'),'preset-one');
    assert.equal(await inputs[1].getAttribute('value'),'sdns://AAAA');
    await driver.executeScript("const s=document.getElementById('custom-server-selection');s.value='preset-two';s.dispatchEvent(new Event('change'))");
    assert.equal(await inputs[1].getAttribute('value'),'sdns://BBBB');
    await driver.findElement(By.xpath('//*[@id="custom-servers"]/div/div[1]/button[text()="Изменить"]')).click();
    assert.equal(await driver.findElement(By.id('custom-server-selection')).getAttribute('value'),'preset-one');
    assert.equal(await inputs[1].getAttribute('value'),'sdns://AAAA');
    await driver.executeScript("const s=document.getElementById('custom-server-selection');s.value='';s.dispatchEvent(new Event('change'))");
    assert.equal(await inputs[1].getAttribute('value'),'');
    await inputs[0].sendKeys('xbox-doh');
    await inputs[1].sendKeys('sdns://AgcAAAAAAAAAAAALeGJveC1kbnMucnUKL2Rucy1xdWVyeQ');
    await driver.findElement(By.xpath('//button[text()="Сохранить кастомный сервер"]')).click();
    await driver.wait(()=>driver.executeScript('return window.savedReload||false'),3000);
    const config=await driver.executeScript('return files[Object.keys(files)[0]]');
    assert.match(config,/\[static\.xbox-doh\]\nstamp = "sdns:\/\/Agc/);
    assert.ok(config.includes('[sources.public]'));
    assert.ok(config.includes('&region=eu </textarea>'));
    assert.equal(await driver.executeScript('return commands.length'),0,'Saving a custom server does not restart DNS');
    await driver.navigate().refresh();
    await driver.wait(()=>driver.executeScript('return window.ready||false'),3000);
    await driver.executeScript('files["/etc/dnscrypt-proxy2/forwarding-rules.txt"]="example.test 127.0.0.1:5300"');
    await driver.findElement(By.css('#tab-rules a')).click();
    await driver.findElement(By.xpath('//div[@id="panel-rules"]//button[text()="Загрузить файл"]')).click();
    await driver.wait(()=>driver.executeScript('return !document.querySelector("#panel-rules textarea").disabled'),3000);
    await driver.findElement(By.xpath('//div[@id="panel-rules"]//button[text()="Использовать этот файл для инстанса"]')).click();
    await driver.wait(()=>driver.executeScript('return window.savedReload||false'),3000);
    const connected=await driver.executeScript('return files[Object.keys(files)[0]]');
    assert.match(connected,/forwarding_rules = ["']\/etc\/dnscrypt-proxy2\/forwarding-rules\.txt["']/);
    assert.ok(connected.indexOf('forwarding_rules')<connected.indexOf('[sources.public]'));
    assert.equal(await driver.executeScript('return commands.length'),0,'Connecting rules does not restart DNS');
    await driver.findElement(By.css('#tab-network a')).click();
    assert.equal(await driver.findElement(By.css('[name="force_tcp"]')).isDisplayed(),true);
    assert.equal(await driver.findElement(By.css('[name="bootstrap_resolvers"]')).isDisplayed(),true);
    assert.equal((await driver.findElements(By.css('#panel-advanced [name="force_tcp"]'))).length,0);
    await driver.findElement(By.css('#tab-catalog a')).click();
    assert.match(await driver.findElement(By.id('panel-catalog')).getText(),/resolvers.md/);
    await driver.findElement(By.id('catalog-select')).click();
    await driver.wait(()=>driver.executeScript('return commands.length>0'),3000);
    assert.deepEqual(await driver.executeScript('return commands[0][1]'),['-config','/etc/dnscrypt-proxy2/dnscrypt-proxy.toml','-list-all','-json']);
    await driver.executeScript('document.getElementById("catalog-results").replaceChildren()');
    await driver.findElement(By.css('#tab-rules a')).click();
    await driver.executeScript("const s=document.querySelector('#panel-rules select');s.value='cloaking';s.dispatchEvent(new Event('change'))");
    assert.match(await driver.findElement(By.css('#panel-rules .rule-connection')).getText(),/уже используется/);
    const use=await driver.findElement(By.xpath('//div[@id="panel-rules"]//button[text()="Использовать этот файл для инстанса"]'));
    assert.equal(await use.isEnabled(),false);
    await driver.executeScript('window.confirm=()=>true;window.savedReload=false');
    await driver.findElement(By.xpath('//div[@id="panel-rules"]//button[text()="Не использовать эти правила"]')).click();
    await driver.wait(()=>driver.executeScript('return window.savedReload||false'),3000);
    assert.equal(await driver.executeScript('return /^cloaking_rules\\s*=/m.test(files[Object.keys(files)[0]])'),false);
    assert.deepEqual(await driver.executeScript('return errors'),[]);
    if(process.env.FORGE_SCREENSHOT)fs.writeFileSync(process.env.FORGE_SCREENSHOT,await driver.takeScreenshot(),'base64');
    console.log('Passed feedback UI: existing stamps auto-loaded and visible, new server, rule connection status/disconnect, separate Network and catalog reload');
  } finally {if(driver)await driver.quit();await new Promise(resolve=>server.close(resolve));}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
